#!/usr/bin/env python3
"""
Offline Cost Analysis Tool

Analyzes cost log CSV files generated by CostLogger.
Provides statistical analysis, correlations, and visualizations.

Usage:
    python analyze_cost_log.py cost_log.csv
    python analyze_cost_log.py cost_log.csv --compare baseline_log.csv
    python analyze_cost_log.py cost_log.csv --save-report analysis_report.pdf
"""

import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


def load_cost_log(filename):
    """Load cost log CSV file."""
    df = pd.read_csv(filename)
    return df


def print_summary_statistics(df, label=""):
    """Print summary statistics for all costs."""
    costs = ['control', 'speed_toward', 'ref_speed', 'collision', 
             'ref_traj', 'goal_pos', 'goal_angle', 'total']
    
    print(f"\n{'='*70}")
    print(f"Summary Statistics {label}")
    print(f"{'='*70}")
    
    for cost in costs:
        if cost in df.columns:
            print(f"\n{cost.upper().replace('_', ' ')}:")
            print(f"  Mean:   {df[cost].mean():8.4f}")
            print(f"  Std:    {df[cost].std():8.4f}")
            print(f"  Min:    {df[cost].min():8.4f}")
            print(f"  Max:    {df[cost].max():8.4f}")
            print(f"  Median: {df[cost].median():8.4f}")


def analyze_phases(df):
    """Analyze costs by navigation phase (early, mid, late)."""
    n_steps = len(df)
    early = df[df['step'] < n_steps * 0.3]
    mid = df[(df['step'] >= n_steps * 0.3) & (df['step'] < n_steps * 0.7)]
    late = df[df['step'] >= n_steps * 0.7]
    
    print(f"\n{'='*70}")
    print("Phase-Based Analysis")
    print(f"{'='*70}")
    
    phases = [('Early (0-30%)', early), ('Mid (30-70%)', mid), ('Late (70-100%)', late)]
    
    for phase_name, phase_df in phases:
        if len(phase_df) > 0:
            print(f"\n{phase_name}:")
            print(f"  Total Cost:     {phase_df['total'].mean():.4f} ± {phase_df['total'].std():.4f}")
            print(f"  Collision Cost: {phase_df['collision'].mean():.4f} ± {phase_df['collision'].std():.4f}")
            print(f"  Goal Pos Cost:  {phase_df['goal_pos'].mean():.4f} ± {phase_df['goal_pos'].std():.4f}")
            if 'goal_distance' in phase_df.columns:
                print(f"  Goal Distance:  {phase_df['goal_distance'].mean():.2f}m")


def compute_correlations(df):
    """Compute and display cost correlations."""
    cost_cols = ['control', 'speed_toward', 'ref_speed', 'collision', 
                 'ref_traj', 'goal_pos', 'goal_angle', 'total']
    state_cols = ['goal_distance', 'min_obstacle_dist', 'goal_yaw_error']
    
    available_cols = [c for c in cost_cols + state_cols if c in df.columns]
    
    if len(available_cols) < 2:
        return
    
    corr_matrix = df[available_cols].corr()
    
    print(f"\n{'='*70}")
    print("Cost Correlations")
    print(f"{'='*70}")
    
    # Highlight interesting correlations
    print("\nStrong Correlations (|r| > 0.5):")
    for i, col1 in enumerate(available_cols):
        for col2 in available_cols[i+1:]:
            corr = corr_matrix.loc[col1, col2]
            if abs(corr) > 0.5:
                print(f"  {col1:20s} <-> {col2:20s}: {corr:6.3f}")


def plot_cost_evolution(df, save_path=None):
    """Create comprehensive cost evolution plots."""
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle('Cost Evolution Analysis', fontsize=16, fontweight='bold')
    
    from matplotlib.gridspec import GridSpec
    gs = GridSpec(3, 3, figure=fig, hspace=0.3, wspace=0.3)
    
    # 1. Total cost
    ax1 = fig.add_subplot(gs[0, :])
    ax1.plot(df['step'], df['total'], 'k-', linewidth=2)
    ax1.fill_between(df['step'], 0, df['total'], alpha=0.3)
    ax1.set_title('Total Cost Evolution', fontweight='bold')
    ax1.set_ylabel('Total Cost')
    ax1.grid(True, alpha=0.3)
    
    # 2. Individual costs
    ax2 = fig.add_subplot(gs[1, 0])
    ax2.plot(df['step'], df['control'], 'b-', label='Control')
    ax2.set_title('Control Cost (Smoothness)')
    ax2.set_ylabel('Cost')
    ax2.grid(True, alpha=0.3)
    ax2.legend()
    
    ax3 = fig.add_subplot(gs[1, 1])
    if 'goal_pos' in df.columns and 'goal_angle' in df.columns:
        ax3.plot(df['step'], df['goal_pos'], 'g-', label='Position')
        ax3.plot(df['step'], df['goal_angle'], 'orange', label='Angle')
    ax3.set_title('Goal Costs (Nav2)')
    ax3.set_ylabel('Cost')
    ax3.grid(True, alpha=0.3)
    ax3.legend()
    
    ax4 = fig.add_subplot(gs[1, 2])
    ax4.plot(df['step'], df['collision'], 'r-', label='Collision')
    ax4.fill_between(df['step'], 0, df['collision'], alpha=0.3, color='red')
    ax4.set_title('Collision Cost')
    ax4.set_ylabel('Cost')
    ax4.grid(True, alpha=0.3)
    ax4.legend()
    
    # 3. State information
    ax5 = fig.add_subplot(gs[2, 0])
    if 'goal_distance' in df.columns:
        ax5.plot(df['step'], df['goal_distance'], 'g-', linewidth=2)
        ax5.set_title('Distance to Goal')
        ax5.set_ylabel('Distance (m)')
        ax5.grid(True, alpha=0.3)
    
    ax6 = fig.add_subplot(gs[2, 1])
    if 'min_obstacle_dist' in df.columns:
        ax6.plot(df['step'], df['min_obstacle_dist'], 'r-', linewidth=2)
        ax6.set_title('Minimum Obstacle Distance')
        ax6.set_ylabel('Distance (m)')
        ax6.grid(True, alpha=0.3)
    
    # 4. Cost distribution
    ax7 = fig.add_subplot(gs[2, 2])
    costs = {
        'Control': df['control'].mean(),
        'Goal Pos': df['goal_pos'].mean() if 'goal_pos' in df.columns else 0,
        'Goal Angle': df['goal_angle'].mean() if 'goal_angle' in df.columns else 0,
        'Collision': df['collision'].mean(),
        'Speed': df['speed_toward'].mean() + df['ref_speed'].mean(),
        'Ref Traj': df['ref_traj'].mean() if 'ref_traj' in df.columns else 0,
    }
    costs = {k: abs(v) for k, v in costs.items() if abs(v) > 0.001}
    
    if costs:
        colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8', '#F7DC6F']
        ax7.pie(costs.values(), labels=costs.keys(), autopct='%1.1f%%',
               startangle=90, colors=colors[:len(costs)])
        ax7.set_title('Average Cost Breakdown')
    
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"\nPlot saved to {save_path}")
    else:
        plt.show()


def compare_logs(df1, df2, label1="Baseline", label2="Modified"):
    """Compare two cost logs."""
    print(f"\n{'='*70}")
    print(f"Comparison: {label1} vs {label2}")
    print(f"{'='*70}")
    
    metrics = ['total', 'collision', 'control', 'goal_pos', 'goal_angle']
    
    print(f"\n{'Metric':<20} {label1:>15} {label2:>15} {'Difference':>15}")
    print("-" * 70)
    
    for metric in metrics:
        if metric in df1.columns and metric in df2.columns:
            val1 = df1[metric].mean()
            val2 = df2[metric].mean()
            diff = val2 - val1
            pct = (diff / val1 * 100) if val1 != 0 else 0
            
            print(f"{metric.upper():<20} {val1:15.4f} {val2:15.4f} "
                  f"{diff:+10.4f} ({pct:+5.1f}%)")
    
    # Check performance metrics
    if 'goal_distance' in df1.columns and 'goal_distance' in df2.columns:
        final_dist1 = df1['goal_distance'].iloc[-1]
        final_dist2 = df2['goal_distance'].iloc[-1]
        
        print(f"\n{'Final Goal Distance':<20} {final_dist1:15.2f}m {final_dist2:15.2f}m")
        
        # Check if goal was reached
        reached1 = final_dist1 < 0.3
        reached2 = final_dist2 < 0.3
        
        print(f"{'Goal Reached?':<20} {str(reached1):>15} {str(reached2):>15}")


def generate_tuning_recommendations(df):
    """Generate parameter tuning recommendations based on log analysis."""
    print(f"\n{'='*70}")
    print("Automated Tuning Recommendations")
    print(f"{'='*70}")
    
    recommendations = []
    
    # Analyze collision cost
    if df['collision'].mean() > 2.0:
        recommendations.append("⚠️  HIGH COLLISION COST: Increase w_collision or reduce d_safe")
    elif df['collision'].mean() < 0.1:
        recommendations.append("✓  Collision cost is low - obstacle avoidance working well")
    
    # Analyze goal convergence
    if 'goal_distance' in df.columns:
        final_dist = df['goal_distance'].iloc[-1]
        if final_dist > 0.5 and df['goal_pos'].mean() > 1.0:
            recommendations.append("⚠️  POOR GOAL CONVERGENCE: Increase w_goal_traj_pos")
    
    # Analyze control smoothness
    if df['control'].std() > 0.5:
        recommendations.append("⚠️  HIGH CONTROL VARIANCE: Increase w_control for smoother motion")
    elif df['control'].mean() < 0.01:
        recommendations.append("✓  Smooth control - w_control tuned well")
    
    # Analyze path following
    if 'ref_traj' in df.columns and df['ref_traj'].mean() > 1.0:
        recommendations.append("⚠️  HIGH PATH DEVIATION: Increase w_ref_traj")
    
    if not recommendations:
        recommendations.append("✓  All costs appear reasonably balanced!")
    
    for rec in recommendations:
        print(f"  {rec}")


def main():
    parser = argparse.ArgumentParser(
        description='Analyze MPPI cost log files'
    )
    parser.add_argument('logfile', type=str,
                       help='Path to cost log CSV file')
    parser.add_argument('--compare', type=str, default=None,
                       help='Path to second log file for comparison')
    parser.add_argument('--save-plot', type=str, default=None,
                       help='Save plot to file instead of displaying')
    parser.add_argument('--no-plot', action='store_true',
                       help='Skip plotting (analysis only)')
    
    args = parser.parse_args()
    
    # Load primary log
    print(f"Loading {args.logfile}...")
    df = load_cost_log(args.logfile)
    
    # Print summary statistics
    print_summary_statistics(df)
    
    # Phase analysis
    analyze_phases(df)
    
    # Correlation analysis
    compute_correlations(df)
    
    # Tuning recommendations
    generate_tuning_recommendations(df)
    
    # Comparison mode
    if args.compare:
        print(f"\nLoading comparison file {args.compare}...")
        df2 = load_cost_log(args.compare)
        compare_logs(df, df2, 
                    label1=Path(args.logfile).stem,
                    label2=Path(args.compare).stem)
    
    # Plotting
    if not args.no_plot:
        plot_cost_evolution(df, save_path=args.save_plot)


if __name__ == '__main__':
    main()
